name: Call a reusable workflow Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      deploy_target:
        required: true
        type: string

jobs:
  #call-workflow:
    #uses: codeclubbentleigh/hello-action/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: codeclubbentleigh/hello-workflow/.github/workflows/called.yml@main
    with:      
      config-path: .github/labeler.yml  
      # name-env: ${{"name-env"}}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
# comment
# comment
